### ISSUE TITLE
Cannot read property 'bullets' of undefined

### ISSUE THREAD

**Issue by selma-li** [wechat-miniprogram/miniprogram-barrage#5]
小程序错误日志如下
``` bash
Cannot read property 'bullets' of undefined
TypeError: Cannot read property 'bullets' of undefined
at t.animationend (https://miniprogram_npm/miniprogram-barrage/index.js:760:25)
at it.onAnimationend (https://miniprogram_npm/miniprogram-barrage/index.js:213:28)
```

看了代码是tunnel不存在时，tunnel.bullets会报错。已提pr [#3](https://github.com/wechat-miniprogram/miniprogram-barrage/pull/3)

**Comment by wechat-miniprogram-admin** [comment]
fix at 1.1.1 version
